HEEEEELLLLLOOOOOO
/Users/sgouyoub/Documents/euclid/Spaceborne_covg/config/example_config_namaster.yaml
file :  <_io.TextIOWrapper name='/Users/sgouyoub/Documents/euclid/Spaceborne_covg/config/example_config_namaster.yaml' mode='r' encoding='UTF-8'>
None
/Users/sgouyoub/Documents/euclid
