# options for the 3x2pt Gaussian covariance matrix computation
# Author: Davide Sciotti

zbins: 6 # number of redshift bins
EP_or_ED: "EP" # or 'ED'. Equipopulated or equidistant redshift bins

ell_min: 10 # minimum ell for the angular power spectra
ell_max: 3000 # maximum ell for the angular power spectra
ell_bins: 32 # number of ell bins for the angular power spectra

# alternatively, one can specify the ell grid directly (set to "null" if you prefer to use ell_min, ell_max, ell_bins)
# ell_path: '../input/ell_values.txt'  # path to txt file with the ell grid
# delta_ell_path: '../input/delta_ell_values.txt' # path to txt file with the delta ell grid
ell_path: null
delta_ell_path: null

# number of sources per arcmin^2, relevant for weak lensing cosmic shear.
# This must one of either:
# - a scalar, for equipopulated ('EP') redshift bins; in this case the exact same number of sources per arcmin^2 is assumed for each redshift bin
# - a list of scalars, for equidistant ('ED') redshift bins. A list can also be passed in the EP case,
# and a check on the consistency of the values will be performed (with tolerance EP_check_tol).
# - a path to a .txt/.dat file with the number of sources per arcmin^2 for each redshift value. This must be of
# shape (n_z_points, zbins + 1), where the first column is the redshift and the following columns are the number of
# sources per arcmin^2 for each redshift bin. As in the case above, a consistency check will be performed in the EP case.
n_gal_shear:
  /home/davide/Documenti/Lavoro/Programmi/Spaceborne_covg/input/data_DR1/nofz_sources_6_bins_EP_0.2_2.5_zmin_zmax_nomagcut_subsample_weighted_galaxies.txt
  # same as above but for the number of lenses per arcmin^2, relevant for photometric galaxy clustering.
n_gal_clustering: /home/davide/Documenti/Lavoro/Programmi/Spaceborne_covg/input/data_DR1/nofz_lenses_6_bins_EP_0.2_2.5_zmin_zmax_mag_cut_23p5.txt
# tolerance for the check on the consistency of the number of sources per arcmin^2 for
# equipopulated ('EP') redshift bins. 0.05 is 5%
EP_check_tol: 0.05

# intrinsic ellipticity dispersion *per component*. The total dispersion is sigma_eps = sigma_eps_i * sqrt(2)
sigma_eps_i: 0.26
# which shape noise to use in the shear noise term:
# - "ISTF": uses the formula of arxiv.org/abs/1910.09273, i.e., shear_noise = sigma_eps**2 / n_bar_shear
# - "per_component": uses the more widely used EE-only noise, i.e., shear_noise = sigma_eps_i**2 / n_bar_shear
which_shape_noise: per_component

survey_area: 1100 # sky coverage, in in deg^2

# datavector and covariance ordering options
triu_tril: "triu" # or 'triu' or 'tril'. Which elements of the (symmetric) auto-spectra are kept
row_col_major: "row-major" # 'row-major' or 'column-major' whether the flattening of the spectra is in row-major or column-major order
covariance_ordering_2D: "probe_ell_zpair" # must be one of ['probe_ell_zpair', 'probe_zpair_ell', 'ell_probe_zpair', 'zpair_probe_ell']
# the naming convention is to have the outermost loop on the left, and the innermost loop on the right; so, e.g.,
# probe_ell_zpair means that the outermost loop is on the probes, the middle loop is on ell and the innermost loop is on zpair
# CLOE v1 needs as input the ell_probe_zpair ordering.
# CLOE v2 needs as input the probe_ell_zpair ordering.
plot_covariance_2D: true # whether to plot (the log10 of) the 2D covariance matrix

# path to 3d numpy Cls
# cl_LL_3D_path: "../input/Cl_LL.npy"
# cl_GL_3D_path: "../input/Cl_GL.npy"
# cl_GG_3D_path: "../input/Cl_GG.npy"

output_folder: "../output"
